dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
networks:
  default: development
  development:
    address_to_contract: '0x5B38Da6a701c568545dCfcB03FcB875f56beddC4'
    address_to_contract_two: '0xAb8483F64d9C6d1EcF9b849Ae677dD3315835cb2'
  kovan:
    address_to_contract: '0x5B38Da6a701c568545dCfcB03FcB875f56beddC4'
    address_to_contract_two: '0xAb8483F64d9C6d1EcF9b849Ae677dD3315835cb2'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}